{% set name = "python-multipart" %}
{% set version = "0.0.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/python_multipart/python_multipart-{{ version }}.tar.gz
  sha256: 7be357d5aec4b59cc4e4999a7e442dfc7eb0c6c0126422ae22c1f2f50ceab6a7

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vvv"

requirements:
  host:
    - hatchling
    - python >=3.8
    - pip
  run:
    - python >=3.8

test:
  imports:
    - python_multipart
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Kludex/python-multipart
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'A streaming multipart parser for Python.'
  description: |
    python-multipart is an Apache2 licensed streaming multipart parser for Python.
    It's still under some development, but test coverage is currently 100%.
    Documentation is available [here](http://andrew-d.github.io/python-multipart/).
  doc_url: https://multipart.fastapiexpert.com
  dev_url: https://github.com/Kludex/python-multipart

extra:
  recipe-maintainers:
    - carlodri
    - thewchan
    - davidbrochart
