{% set name = "python-multipart" %}
{% set version = "0.0.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/python_multipart/python_multipart-{{ version }}.tar.gz
  sha256: 7a68db60c8bfb82e460637fa4750727b45af1d5e2ed215593f917f64694d34fe

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vvv"

requirements:
  host:
    - hatchling
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - python_multipart
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Kludex/python-multipart
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'A streaming multipart parser for Python.'
  description: |
    python-multipart is an Apache2 licensed streaming multipart parser for Python.
    It's still under some development, but test coverage is currently 100%.
    Documentation is available [here](http://andrew-d.github.io/python-multipart/).
  doc_url: https://multipart.fastapiexpert.com
  dev_url: https://github.com/Kludex/python-multipart

extra:
  recipe-maintainers:
    - carlodri
    - thewchan
    - davidbrochart
