{% set name = "python-multipart" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e9925a80bb668529f1b67c7fdb0a5dacdd7cbfc6fb0bff3ea443fe22bdd62132

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vvv"

requirements:
  host:
    - hatchling
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - multipart
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/andrew-d/python-multipart
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'A streaming multipart parser for Python.'
  description: |
    python-multipart is an Apache2 licensed streaming multipart parser for Python.
    It's still under some development, but test coverage is currently 100%.
    Documentation is available [here](http://andrew-d.github.io/python-multipart/).
  doc_url: http://andrew-d.github.io/python-multipart/
  dev_url: https://github.com/andrew-d/python-multipart

extra:
  recipe-maintainers:
    - carlodri
    - thewchan
